export const FETCHING = "USER/FETCHING";
export const FETCH_FAILURE = "USER/FETCH_FAILURE";

export const LOGIN_FETCH = "USER/LOGIN_FETCH";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER/LOGIN_FAILURE";

export const TFA_SUCCESS = "USER/TFA_SUCCESS";
export const TFA_FAILURE = "USER/TFA_FAILURE";

export const TFA_GENERATE_SUCCESS = "USER/TFA_GENERATE_SUCCESS";
export const TFA_GENERATE_FAILURE = "USER/TFA_GENERATE_FAILURE";

export const TFA_ENABLE_SUCCESS = "USER/TFA_ENABLE_SUCCESS";
export const TFA_ENABLE_FAILURE = "USER/TFA_ENABLE_FAILURE";

export const LOGOUT = "USER/LOGOUT";

export const REGISTER_FETCH = "USER/REGISTER_FETCH";
export const REGISTER_SUCCESS = "USER/REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER/REGISTER_FAILURE";

export const CLEAR_QR_CODE = "USER/CLEAR_QR_CODE";
